name: Deploy to Cloud Server

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn
      - run: yarn build
      - name: Prepare static assets
        run: |
          cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: view foler list
        run: ls
      - name: Deploy to Cloud Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: '.next/standalone/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/var/www/'
          SCRIPT_AFTER: |
            cd /var/www
            pm2 start server.js --name blog-app || pm2 restart blog-app
